export const ERROR_USER_NOT_FOUND = 'ERROR_USER_NOT_FOUND';
export const ERROR_USER_NAME_OR_PASSWORD_WRONG = 'ERROR_USER_NAME_OR_PASSWORD_WRONG';
export const ERROR_USER_UUId_WRONG = 'ERROR_USER_UUId_WRONG';
export const ERROR_USER_NAME_WRONG = 'ERROR_USER_NAME_WRONG';
export const ERROR_USER_PASSWORD_WRONG = 'ERROR_USER_PASSWORD_WRONG';
export const ERROR_UNKNOWN_USER_LOGIN_ERROR = 'ERROR_UNKNOWN_USER_LOGIN_ERROR';
export const ERROR_UNKNOWN_USER_REGISTER_ERROR = 'ERROR_UNKNOWN_USER_REGISTER_ERROR';
export const ERROR_ALREADY_LOGGED_IN = 'ERROR_ALREADY_LOGGED_IN';
export const ERROR_NOT_LOGGED_IN = 'ERROR_NOT_LOGGED_IN';

export const INFO_USER_LOGIN_SUCCEEDED = 'INFO_USER_LOGIN_SUCCEEDED';
export const INFO_USER_REGISTER_SUCCEEDED = 'INFO_USER_REGISTER_SUCCEEDED';