const ERROR_USER_NOT_FOUND = 'ERROR_USER_NOT_FOUND';
const ERROR_USER_NAME_OR_PASSWORD_WRONG = 'ERROR_USER_NAME_OR_PASSWORD_WRONG';
const ERROR_USER_UUId_WRONG = 'ERROR_USER_UUId_WRONG';
const ERROR_USER_NAME_WRONG = 'ERROR_USER_NAME_WRONG';
const ERROR_USER_PASSWORD_WRONG = 'ERROR_USER_PASSWORD_WRONG';
const ERROR_UNKNOWN_USER_LOGIN_ERROR = 'ERROR_UNKNOWN_USER_LOGIN_ERROR';

const INFO_USER_LOGIN_SUCCEEDED = 'INFO_USER_LOGIN_SUCCEEDED';

module.exports = {
  ERROR_USER_NOT_FOUND,
   ERROR_USER_NAME_OR_PASSWORD_WRONG,
   ERROR_USER_UUId_WRONG,
   ERROR_USER_NAME_WRONG,
   ERROR_USER_PASSWORD_WRONG,
   ERROR_UNKNOWN_USER_LOGIN_ERROR,
  
  INFO_USER_LOGIN_SUCCEEDED
};